### ISSUE TITLE
File "/app/main.py", line 39, in <module>

### ISSUE THREAD

**Issue by WenLiCG** [Akimio521/AutoFilm#130]
可以看一下我的吗？
感谢
docker 错误信息如下：
```
[32m【INFO】[0m 2025-06-05 15:56:56 | AutoFilm v1.3.3-2 启动中...
[32m【INFO】[0m 2025-06-05 15:56:56 | 检测到 Alist2Strm 模块配置，正在添加至后台任务
Traceback (most recent call last):
File "/app/main.py", line 39, in <module>
Alist2Strm(**server).run, trigger=CronTrigger.from_crontab(cron)
^^^^^^^^^^^^^^^^^^^^
TypeError: Argument 'other_ext' has incorrect type (expected str, got NoneType)

█████╗ ██╗ ██╗████████╗ ██████╗ ███████╗██╗██╗ ███╗ ███╗
██╔══██╗██║ ██║╚══██╔══╝██╔═══██╗██╔════╝██║██║ ████╗ ████║
███████║██║ ██║ ██║ ██║ ██║█████╗ ██║██║ ██╔████╔██║
██╔══██║██║ ██║ ██║ ██║ ██║██╔══╝ ██║██║ ██║╚██╔╝██║
██║ ██║╚██████╔╝ ██║ ╚██████╔╝██║ ██║███████╗██║ ╚═╝ ██║
╚═╝ ╚═╝ ╚═════╝ ╚═╝ ╚═════╝ ╚═╝ ╚═╝╚══════╝╚═╝ ╚═╝

======================= Autofilm v1.3.3-2 =======================
```

配置过程如下：
mkdir -p /root/autofilm/config
vi /root/autofilm/config/config.yaml

```
Settings:
  DEV: False                          # 开发者模式(可选，默认 False)

Alist2StrmList:
  - id: 美剧                          # 标识 ID
    cron: 0 20 * * *                  # 后台定时任务 Crontable 表达式
    url: http://23.165.248.XXX:5244   # Alist 服务器地址
    username: xxx
    password: xxx
    source_dir: /video2/test/         # Alist 服务器上文件夹路径,为存放需要转化为Strm文件的路径，程序会遍历其子路径
    target_dir: /root/autofilm/media/ # 本地Strm文件的存放目录，建议使用绝对路径，相对路径可能出现找不到文件的情况
    flatten_mode: False               # 平铺模式，开启后 subtitle、image、nfo 强制关闭(可选，默认 False)
    subtitle: False                   # 是否下载字幕文件（可选，默认 False）
    image: False                      # 是否下载图片文件（可选，默认 False）
    nfo: False                        # 是否下载 .nfo 文件（可选，默认 False）
    raw_url: False                    # 是否使用原始地址替换 Alist 服务器下载地址（可选，默认 False）
    overwrite: False                  # 覆盖模式，本地路径存在同名文件时是否重新生成/下载该文件（可选，默认 False）
    other_ext:                        # 自定义下载后缀，使用西文半角逗号进行分割，（可选，默认为空）
    max_workers: 5                    # 下载文件最大并发数（可选，默认 5）
```
 
cd /root/autofilm
docker run -d --name autofilm  -v ./config:/config -v ./media:/media -v./logs:/logs akimio/autofilm
