### ISSUE TITLE
Alist令牌token读取错误

### ISSUE THREAD

**Issue by 1715819** [Akimio521/AutoFilm#23]
已经设置好了token，但是为什么识别不出来呢

**Comment by Akimio521** [comment]
没有设置 token 就会有这个提示，默认值为空，注意 yaml 格式的缩进

**Comment by 1715819** [comment]
解决了，谢谢。
还有一个问题就是网页端可以播放，但是用jellyfin app播放或者用外部播放器（vlc）播放还是有问题，会出现流量走的是vps而且vps内存爆满的情况

**Comment by Akimio521** [comment]
> 解决了，谢谢。
> 
> 还有一个问题就是网页端可以播放，但是用jellyfin app播放或者用外部播放器（vlc）播放还是有问题，会出现流量走的是vps而且vps内存爆满的情况

这个要看jellyfin和 alist 部署在哪里，如果没有token 获取问题我就关闭此 issue 了

**Comment by 1715819** [comment]
好的，谢谢

**Comment by Akimio521** [comment]
> 同样遇到此问题，我是直接修改的示例配置文件，并没有修改缩进，依旧出现了这个问题
> 
> ```
> 
> setting:
> 
>   output_path: ./test/     # 输出路径
> 
>   l_threads: 3              # list_files线程数
> 
>   p_threads: 8              # processing_file线程数
> 
>   subtitle: True            # 是否下载字幕
> 
>   img: True                # 是否下载图片
> 
>   nfo: True                 # 是否下载视频信息文件
> 
>   url_encode: True          # 是否对生成的strm文件中的链接进行URL编码
> 
> webdav:
> 
>   我的Alist:
> 
>     url: https://example.com/dav
> 
>     username: 123
> 
>     password: "abcc"
> 
>     token: "alist-ddddddddddddddddd"
> 
> ```

把双引号移除，yaml不需要双引号

**Comment by 1715819** [comment]
这样写没问题：
```yaml
setting:
  output_path: /home/media/     # 输出路径
  l_threads: 3              # list_files 线程数
  p_threads: 8              # processing_file 线程数
  subtitle: True            # 是否下载字幕
  img: False                # 是否下载图片
  nfo: True                 # 是否下载视频信息文件
webdav:
  动漫A:                                        # 任意字符，用于标识 Webdav 服务器
    url: https://al.chirmyram.com/dav/ani/A/    # Webdav 服务器 URL
    username: alist                             # Webdav 账号
    password: alist                             # Webdav 密码
token: "ssssssss"
```
