### ISSUE TITLE
最新版docker 报错

### ISSUE THREAD

**Issue by lin1123** [Akimio521/AutoFilm#30]
错误信息
```
autofilm  | 正在执行主程序...
autofilm  | [2024-06-10 22:06:18,569][INFO]<module>:当前的APP版本是：v1.1.0
autofilm  | [2024-06-10 22:06:18,569][INFO]<module>:配置文件路径：config/config.yaml
autofilm  | [2024-06-10 22:06:18,571][ERROR]__init__:配置文件/app/config/config.yaml读取错误，错误信息：'output_dir'
autofilm  | Traceback (most recent call last):
autofilm  |   File "/app/main.py", line 20, in <module>
autofilm  |     my_autofilm = autofilm.AutoFilm(config_path=args.config_path)
autofilm  |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
autofilm  |   File "/app/autofilm.py", line 56, in __init__
autofilm  |     logging.info(f"输出目录：{self.output_dir}".center(50, "="))
autofilm  |                               ^^^^^^^^^^^^^^^
autofilm  | AttributeError: 'AutoFilm' object has no attribute 'output_dir'
autofilm  | 等待 3600 秒后再次执行...
```
config 配置文件内容
```yaml
Settings:
  output_path: /opt/dockge/stacks/autofilm/media       # ./media    # 输出路径尝试过相关路径与绝对路径，都报这个错误
  subtitle: True            # 是否下载字幕
  img: False                # 是否下载图片
  nfo: True                 # 是否下载视频信息文件

AlistServerList:
  - id: X                                   
    url: "https://alist.example.com"
    username: alist
    password: "password"
    base_path: /xunlei-1/media
```

**Comment by lin1123** [comment]
docker compose 文件
```yaml
services:
  autofilm:
    container_name: autofilm
    volumes:
      - ./config:/app/config
      - ./media:/app/media
    environment:
      - INTERVAL=3600
    image: akimio/autofilm
    networks:
      - npm
    restart: unless-stopped
networks:
  npm:
    external: true
```
