### ISSUE TITLE
docker存放位置错误

### ISSUE THREAD

**Issue by FeranyDev** [Akimio521/AutoFilm#31]
1. docker运行时会将strm存放的base目录选定为docker内部的根目录，打印的日志缺没有问题，无论library_mode设置为True还是False。
![图片](https://github.com/Akimio521/AutoFilm/assets/43532576/4d026078-6d4f-475c-8b80-85a654c40ff3)
排查后发现[这里](https://github.com/Akimio521/AutoFilm/blob/main/autofilm.py#L124)在最后加上```.lstrip("/")```无论library_mode设置为True还是False都可以正常写入配置文件中output_dir所指定的位置。
2. 多次观察到library_mode 设置为True 还是 False 最后输出的文件结构似乎是一样的，他们应该有什么不同？看源码文件是否应该平铺在output_dir路径下？平铺是否会涉及到文件名相同的情况，使用什么规则重命名？

**Comment by Akimio521** [comment]
docker 版本目前为 v1.1.0，无 library_mode 模式，需要使用可以自行部署 python 环境，因为目前相比上个版本更改不多，就没构建镜像了

**Comment by Akimio521** [comment]
版本已更新至v1.1.1，请尝试重新拉取镜像，我已测试python、docker环境下的文件输出目录与library_mode，目前程序运行预期正常

**Comment by FeranyDev** [comment]
docker已更新到1.1.1
![图片](https://github.com/Akimio521/AutoFilm/assets/43532576/e2d11121-f181-44f3-9c72-cc3f8ef570a2)
配置文件如下
```yaml
Settings:
  output_dir: /app/media/   
  subtitle: False
  img: False
  nfo: False
  library_mode: True
AlistServerList:
  - id: 3865U               
    url: http://172.30.0.5:5244/
    username: user
    password: password
    base_path: /Aliyun1/Media
    token:
```
当library_mode 为True的时候内容平铺在docker内的```/app/media/```下正常 
![图片](https://github.com/Akimio521/AutoFilm/assets/43532576/1432ae89-86d7-46cb-88da-7f768d778cd3)
当library_mode 为False的时候内容保存在docker内根目录下
![图片](https://github.com/Akimio521/AutoFilm/assets/43532576/45fc1326-b7c0-4fdf-baea-88f80b4166fa)
两个方式日志如下
![图片](https://github.com/Akimio521/AutoFilm/assets/43532576/c7201c9b-02af-4dbc-80e2-ad701ef0ad89)
alist目录结构如下
![图片](https://github.com/Akimio521/AutoFilm/assets/43532576/48dbc47e-4ec7-4124-901f-bd4475abdcb3)
