### ISSUE TITLE
用docker部署后，运行没有报错，但是没有生成strm文件

### ISSUE THREAD

**Issue by DLL-ss** [Akimio521/AutoFilm#38]
你好，不好意思麻烦帮忙看下哪里设置的有问题，谢谢！

config.yaml配置文件如下：
```
Settings:
  output_dir: media         # 输出路径
  subtitle: False             # 是否下载字幕
  img: False                # 是否下载图片
  nfo: False                  # 是否下载视频信息文件
  library_mode: False       # 媒体库模式

AlistServerList:
  - id: 视频115                       # 任意字符，用于标识Alist服务器
    url: http://192.168.0.100:35244   # Alist服务器URL
    username: admin                  # Alist账号
    password: admin               # Alist密码
    base_path: /115/video/     # Alist服务器上文件夹路径 
    token:       
    async_mode: False                # 设置 subtitle,img,nfo 等二进制文件是否启用异步下载
    overwrite: False # AList未启用签名时，设置为空字符串
```

日志信息如下：
```
<html>
<body>
<!--StartFragment-->
2024/06/30 21:18:32 | stdout | 等待 3600 秒后再次执行...
-- | -- | --
2024/06/30 21:18:31 | stdout | [2024-06-30 21:18:31,627][INFO]__init__:=================输出目录：/app/media==================
2024/06/30 21:18:31 | stdout | [2024-06-30 21:18:31,620][INFO]<module>:配置文件路径：/app/config/config.yaml
2024/06/30 21:18:31 | stdout | [2024-06-30 21:18:31,620][INFO]<module>:当前的APP版本是：v1.1.1-2
2024/06/30 21:18:30 | stdout | 正在执行主程序...

<!--EndFragment-->
</body>
</html>
```
然后我在挂载的media文件夹里没有发现任何文件，通过终端进入docker内部，在/app/media下面也没有任何文件生成。
请问下我这个有什么问题吗，请指教下，谢谢！
