### ISSUE TITLE
每次都运行成功，但每条都报处理失败，6秒后重试 ...

### ISSUE THREAD

**Issue by wangrui1573** [Akimio521/AutoFilm#48]
运行报错，但是去目录查看，STRM、字幕、nfo都在，不知道如何查看报错软银

[WARNING]2024-07-22 16:38:16,680 - /volume2/电影/strm/电视剧/黑镜/Season 06处理失败，6秒后重试 ...
[WARNING]2024-07-22 16:38:17,804 - /volume2/电影/strm/电视剧/黑镜处理失败，6秒后重试 ...
[WARNING]2024-07-22 16:38:17,806 - /volume2/电影/strm/电视剧处理失败，6秒后重试 ...
[WARNING]2024-07-22 16:38:22,682 - /volume2/电影/strm/电视剧/黑镜/Season 06处理失败，超出最大重试次数！返回默认值
[WARNING]2024-07-22 16:38:23,807 - /volume2/电影/strm/电视剧/黑镜处理失败，超出最大重试次数！返回默认值
[WARNING]2024-07-22 16:38:23,807 - /volume2/电影/strm/电视剧处理失败，超出最大重试次数！返回默认值

启动命令：
docker run -d --name autofilm --restart unless-stopped  -v /volume1/docker/emby_strm_autofilm/config:/config -v /volume2/电影/strm:/volume2/电影/strm -v /volume1/docker/emby_strm_autofilm/logs:/logs akimio/autofilm:DEV

配置文件如下：

```
Settings:
  DEV: False                          # 开发者模式(可选，默认 False)

Alist2StrmList:
  - id: 电影                          # 标识 ID
    cron: 30 9-23 * * *                  # 后台定时任务 Crontable 表达式
    url: http://192.168.31.192:5678    # Alist 服务器地址
    username: guest                   # Alist 用户名
    password: guest_Api789             # Alist 密码
    source_dir: /aliyun/Emby/            # Alist 服务器上文件夹路径
    target_dir: /volume2/电影/strm     # 输出路径
    flatten_mode: False               # 平铺模式，开启后 subtitle、image、nfo 强制关闭(可选，默认 False)
    subtitle: True                   # 是否下载字幕文件（可选，默认 False）
    image: True                      # 是否下载图片文件（可选，默认 False）
    nfo: True                        # 是否下载 .nfo 文件（可选，默认 False）
    raw_url: False                    # 是否使用原始地址替换 Alist 服务器下载地址（可选，默认 False）
    overwrite: True                  # 覆盖模式，本地路径存在同名文件时是否重新生成/下载该文件（可选，默认 False）
    other_ext:                        # 自定义下载后缀，使用西文半角逗号进行分割，（可选，默认为空）
    max_workers: 5                    # 下载文件最大并发数（可选，默认 5）
    
  - id: 夸克
    cron: 30 9-23 * * *
    url: http://192.168.31.1:5244
    username: admin
    password: admin
    source_dir: /kuake/Emby/
    target_dir: /volume2/电影/strm
    flatten_mode: False 
    subtitle: True
    image: True
    nfo: True
    raw_url: False
    overwrite: True
    other_ext: 
    max_workers: 5

#Ani2AlistList:
#  - id: 新番追更                           # 标识 ID
#    cron: 20 12 * * *                     # 后台定时任务 Crontable 表达式
#    url: https://127.0.0.1:5244           # Alist 服务器地址
#    username: admin                       # Alist 用户名（需管理员权限）
#    password: myalist                     # Alist 密码
#    target_dir: /视频/动漫/新番            # Alist 地址树存储器路径，若存储器不存在将自动创建（可选，默认/Anime）
#    rss_update: False                     # 使用 RSS 订阅更新最新番剧，启用后忽视传入的 year 和 month（可选，默认为 True）
#    year: 2024                            # 动漫季度-年份，仅支持 2019-1 及以后更新的番剧（可选，默认使用当前日期）
#    month: 7                              # 动漫季度-月份，仅支持 2019-1 及以后更新的番剧（可选，默认使用当前日期）
#    src_domain: aniopen.an-i.workers.dev  # ANI Open 项目域名（可选，默认为 aniopen.an-i.workers.dev）
#    rss_domain: api.ani.rip               # ANI Open 项目 RSS 订阅域名（可选，默认为 api.ani.rip） 
```
